# Generated by Django 3.1.2 on 2020-11-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=38)),
                ('country', models.CharField(max_length=38)),
            ],
        ),
    ]
