# Generated by Django 3.1.2 on 2020-11-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradesman', '0001_initial'),
        ('bill', '0002_auto_20201108_1201'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradesman.tradesman')),
            ],
        ),
    ]
