# Generated by Django 3.1.2 on 2020-11-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_product',
            fields=[
                ('cart_product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.SmallIntegerField()),
                ('price_total', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shopping_cart')),
            ],
        ),
    ]
