# Generated by Django 3.1.3 on 2020-12-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
        ('products', '0002_product_image'),
        ('cart_product', '0002_cart_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('cart_product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.SmallIntegerField()),
                ('price_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shopping_cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
