# Generated by Django 3.1.2 on 2020-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_number', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
