# Generated by Django 3.1.2 on 2020-11-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units_per_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xs_units', models.IntegerField()),
                ('s_units', models.IntegerField()),
                ('m_units', models.IntegerField()),
                ('l_units', models.IntegerField()),
                ('xl_units', models.IntegerField()),
                ('na_units', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
