# Generated by Django 3.1.3 on 2020-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_per_size', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units_per_size',
            name='total_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
