# Generated by Django 3.1.2 on 2020-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradesman',
            fields=[
                ('employer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
