# Generated by Django 3.1.3 on 2020-12-03 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradesman', '0003_auto_20201202_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesman',
            name='auth_user_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
