# Generated by Django 3.1.2 on 2020-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admi',
            fields=[
                ('admi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admi_name', models.CharField(max_length=38)),
                ('admi_last_name', models.CharField(max_length=38)),
            ],
        ),
    ]
