# Generated by Django 3.1.2 on 2020-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
